/* Run with TEST_NODE_MODULES pointing to test dependencies, plus a local HTTP server. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const deps=process.env.TEST_NODE_MODULES||path.resolve(__dirname,'../../testdeps/node_modules');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[path.extname(p)]||'application/json');res.end(fs.readFileSync(p))}catch{res.writeHead(404).end()}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||path.resolve(deps,'../chromium'),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:'+server.address().port+'/';
const qaFont=path.resolve(deps,'../qa-cjk.otf');if(fs.existsSync(qaFont))await context.route('**/styles.css',route=>route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(root,'styles.css'),'utf8')+'\n@font-face{font-family:"PingFang SC";src:url(data:font/otf;base64,'+fs.readFileSync(qaFont).toString('base64')+');font-weight:100 900;font-style:normal}'}));
async function stored(){return page.evaluate(async()=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>{db.close();res(r.result.data)}})})}
async function go(view){await page.locator(`.nav [data-view=${view}]`).click()}
const hasStock=(d,id)=>d.pantryItems.some(i=>i.matches.includes(id));
async function stock(id,checked=true){const name=await page.evaluate(id=>window.MIX_SEED.ingredients.find(i=>i.id===id)?.name,id);await page.locator('#pantry-directory [data-material-search]').fill(name);await page.locator(`#pantry-directory [data-pantry="${id}"]`).setChecked(checked)}
try{
await page.goto(base);await page.waitForSelector('.recipe-card');assert.equal(await page.locator('.recipe-card').count(),102);assert.equal((await stored()).schemaVersion,4);console.log('PASS initial 102 recipes persisted');
const recipeAction=await page.locator('.page-heading>[data-action=new]').boundingBox();await go('pantry');const pantryAction=await page.locator('.page-heading>[data-action=add-pantry-bottle]').boundingBox();assert.equal(pantryAction.y,recipeAction.y);assert.equal(pantryAction.height,recipeAction.height);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-pantry-heading.png'),fullPage:false});await go('recipes');console.log('PASS recipe and pantry page actions share the same top position and height');
await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result)}),saved=await new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>res(r.result)});saved.data.recipes[0].createdAt='2000-01-01T00:00:00.000Z';saved.data.recipes[0].updatedAt='2099-01-01T00:00:00.000Z';saved.data.recipes[1].createdAt='2098-01-01T00:00:00.000Z';saved.data.recipes[1].updatedAt='2000-01-01T00:00:00.000Z';await new Promise(res=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(saved,'current');tx.oncomplete=res});db.close()});await page.reload();await page.waitForSelector('.recipe-card');assert.equal(await page.locator('.recipe-card [data-detail]').first().getAttribute('data-detail'),(await stored()).recipes[1].id);assert.equal(await page.locator('.sort-options').innerText(),'最新\n可制作\n随机');console.log('PASS latest ordering uses creation time and concise controls');
assert.equal(await page.locator('.catalog-photo[src]').count(),59);assert.ok((await page.locator('.catalog-photo[src]').evaluateAll(imgs=>imgs.map(i=>i.getAttribute('src')))).every(s=>/\?v=[0-9a-f]{12}$/.test(s)));await page.locator('.catalog-photo[src]').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode()})));assert.ok((await page.locator('.catalog-photo[src]').evaluateAll(imgs=>imgs.map(i=>({fit:getComputedStyle(i).objectFit,frameRatio:i.clientWidth/i.clientHeight,imageRatio:i.naturalWidth/i.naturalHeight})))).every(({fit,frameRatio,imageRatio})=>fit==='contain'&&Math.abs(frameRatio-imageRatio)<.01));console.log('PASS all 59 recipe photos decode and display uncropped in image-ratio portrait frames with content-version URLs');
await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-desktop.png'),fullPage:false});
await go('settings');await page.locator('[data-action=open-sync-settings]').click();assert.equal(await page.locator('#sync-dialog[open]').count(),1);assert.equal(await page.evaluate(()=>{const d=document.querySelector('#sync-dialog');return d.scrollWidth<=d.clientWidth+1&&d.getBoundingClientRect().right<=innerWidth}),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-sync-desktop.png'),fullPage:false});await page.locator('#sync-dialog [aria-label="关闭同步设置"]').click();await go('recipes');console.log('PASS desktop sync settings modal');
assert.equal(await page.locator('[data-filter=formats],[data-filter=families],[data-filter=bases],#iba-filter,#method-filter').count(),0);
await page.locator('[data-base-filter="金酒"]').click();assert.ok(await page.locator('.recipe-card').count()>0);assert.equal(await page.locator('.recipe-card').evaluateAll(cards=>cards.every(card=>window.MIX_SEED.recipes.find(r=>r.id===card.querySelector('[data-detail]').dataset.detail).base==='金酒')),true);await page.locator('[data-action=reset-filters]').click();console.log('PASS single base-spirit filter');
await page.locator('#source-filter').selectOption('IBA · 当代经典');assert.equal(await page.locator('.recipe-card').count(),34);await page.locator('[data-filter=tags][data-value="酸甜"]').click();assert.ok(await page.locator('.recipe-card').count()>0);assert.ok((await page.locator('.card-no').allTextContents()).every(x=>x.includes('IBA · 当代经典')));assert.ok((await page.locator('.card-tags').allTextContents()).every(x=>x.includes('酸甜')));await page.locator('[data-action=reset-filters]').click();console.log('PASS flavor and single source filters; old classifications absent');
// Simulate an existing v2 browser record and reload through the actual migration path.
await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result)});const saved=await new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>res(r.result)});saved.data.schemaVersion=2;saved.data.catalogVersion='iba-2026-09-21-v2';for(const r of saved.data.recipes){r.ibaCategory=r.sourceName.replace('IBA · ','');delete r.sourceName;r.formats=['短饮'];r.families=['Tiki']}saved.data.recipes[0].notes='升级保留我的笔记';await new Promise(res=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(saved,'current');tx.oncomplete=res});db.close()});await page.reload();await page.waitForSelector('.recipe-card');assert.equal((await stored()).recipes[0].notes,'升级保留我的笔记');assert.equal((await stored()).recipes[0].sourceName,'IBA · 难忘经典');assert.equal((await stored()).recipes[0].families,undefined);console.log('PASS existing v2 browser upgrade');
await go('pantry');assert.equal(await page.locator('[data-pantry]').count(),0);await page.locator('[data-action=pantry-edit]').click();await stock('beefeater');assert.equal(hasStock(await stored(),'beefeater'),false);await page.locator('[data-action=pantry-cancel]').click();assert.equal(hasStock(await stored(),'beefeater'),false);console.log('PASS pantry cancellation does not persist');
await page.locator('[data-action=pantry-edit]').click();for(const id of ['beefeater','campari','dolin-rouge'])await stock(id);await page.locator('[data-action=pantry-save]').click();await page.locator('[data-action=pantry-cancel]').click();await page.waitForSelector('[data-action=pantry-edit]');await page.locator('[data-pantry-section=gin]').click();assert.equal(await page.locator('.bottle-card').count(),1);await page.reload();await page.waitForSelector('.recipe-card');assert.equal(hasStock(await stored(),'dolin-rouge'),true);console.log('PASS pantry save and reload');
await go('pantry');await page.locator('[data-pantry-section=all]').click();assert.doesNotMatch(await page.locator('#pantry-results').innerText(),/未拥有的材料条目/);assert.equal(await page.locator('.bottle-card').count(),3);const campariRecipes=(await stored()).recipes.map(r=>JSON.stringify(r));const ingredientCount=(await stored()).ingredients.length;await page.locator('.bottle-card').filter({hasText:'金巴利'}).click();await page.locator('[data-action=delete-pantry-bottle]').click();await page.screenshot({path:path.resolve(__dirname,'../../mixbook-pantry-delete.png'),fullPage:false});await page.locator('#confirm-dialog [data-choice=yes]').click();let afterDelete=await stored();assert.equal(hasStock(afterDelete,'campari'),false);assert.equal(afterDelete.ingredients.length,ingredientCount);assert.ok(afterDelete.ingredients.some(i=>i.id==='campari'));assert.deepEqual(afterDelete.recipes.map(r=>JSON.stringify(r)),campariRecipes);await page.locator('[data-pantry-group="利口酒"]').click();await page.locator('[data-pantry-section=bitter-aperitif]').click();await page.locator('[data-action=add-pantry-bottle]').click();
const typeDropdown=page.locator('#pantry-bottle-form .type-dropdown'),brandField=page.locator('#pantry-bottle-form [name=brand]');
assert.equal(await page.locator('#pantry-bottle-form [name=name]').getAttribute('placeholder'),'请输入');assert.equal(await brandField.getAttribute('placeholder'),'请输入');assert.equal(await typeDropdown.locator('[data-type-search]').getAttribute('placeholder'),'选择原料分类');
const formSize=await page.locator('#item-dialog').evaluate(el=>({width:el.clientWidth,height:el.clientHeight}));
await typeDropdown.locator('summary').click();
const columnStyle=await page.evaluate(()=>{const left=document.querySelector('.type-drawers'),right=document.querySelector('.type-options'),leftRow=left.querySelector('button'),rightRow=right.querySelector('label span'),ls=getComputedStyle(leftRow),rs=getComputedStyle(rightRow);return{leftWidth:left.getBoundingClientRect().width,rightWidth:right.getBoundingClientRect().width,leftFont:ls.font,leftPadding:ls.padding,rightFont:rs.font,rightPadding:rs.padding}});
assert.ok(Math.abs(columnStyle.leftWidth-columnStyle.rightWidth)<1);assert.equal(columnStyle.leftFont,columnStyle.rightFont);assert.equal(columnStyle.leftPadding,columnStyle.rightPadding);
const overlayLayout=await page.evaluate(()=>{const menu=document.querySelector('.type-cascade').getBoundingClientRect(),brand=document.querySelector('#pantry-bottle-form [name=brand]').getBoundingClientRect();return{overlaps:menu.bottom>brand.top,brandTop:brand.top}});
assert.equal(overlayLayout.overlaps,true);await page.locator('[data-type-drawer=non-alcohol]').hover();assert.equal(await page.locator('[data-type-options=non-alcohol]').isVisible(),true);assert.equal((await brandField.boundingBox()).y,overlayLayout.brandTop);
const drawerCount=await page.locator('[data-type-drawer]').count();await typeDropdown.locator('[data-type-search]').fill('果汁');assert.equal(await page.locator('[data-type-drawer]').count(),drawerCount);assert.ok((await page.locator('.type-options [data-type-name]:visible').allTextContents()).every(name=>name.includes('果汁')));assert.deepEqual(await page.locator('#item-dialog').evaluate(el=>({width:el.clientWidth,height:el.clientHeight})),formSize);await typeDropdown.locator('[data-type-search]').fill('');
await page.screenshot({path:path.resolve(__dirname,'../../mixbook-pantry-type-dropdown.png'),fullPage:false});
await page.locator('#pantry-bottle-form .field').first().click({position:{x:5,y:5}});assert.equal(await typeDropdown.getAttribute('open'),null);
await page.locator('#pantry-bottle-form [name=name]').fill('金巴利');await page.locator('#pantry-bottle-form button[type=submit]').click();assert.equal(hasStock(await stored(),'campari'),true);assert.equal((await stored()).ingredients.length,ingredientCount);
await page.locator('[data-action=add-pantry-bottle]').click();await page.locator('#pantry-bottle-form [data-type-drawer=other-alcohol]').hover();await page.locator('#pantry-bottle-form [name=rootId][value=aperitif]').check();await page.locator('#pantry-bottle-form [name=name]').fill('金巴利');await page.locator('#pantry-bottle-form button[type=submit]').click();assert.ok((await stored()).pantryItems.some(i=>i.name==='金巴利'&&i.matches.includes('aperitif')));console.log('PASS an explicitly selected pantry category wins over a same-name catalog product in another category');
await page.locator('[data-action=pantry-edit]').click();await stock('gin');await page.locator('[data-action=pantry-save]').click();await page.locator('[data-action=pantry-cancel]').click();await page.locator('[data-pantry-section=all]').click();await page.locator('.bottle-card').filter({has:page.getByRole('heading',{name:'金酒',exact:true})}).click();await page.locator('[data-action=delete-pantry-bottle]').click();await page.locator('#confirm-dialog [data-choice=yes]').click();assert.equal(hasStock(await stored(),'gin'),false);assert.ok((await stored()).ingredients.some(i=>i.id==='gin'));await go('recipes');console.log('PASS pantry records delete completely, recipes stay unchanged, and same-name records can be added again');
await page.locator('#recipe-search').fill('Negroni');await page.locator('[data-detail=iba-negroni].card-main').click();assert.match(await page.locator('#detail-dialog').innerText(),/材料齐全/);assert.equal(await page.locator('.recipe-source').innerText(),'来源：IBA · 难忘经典');assert.match(await page.locator('#detail-dialog').innerText(),/酒柜：杜林/);
await page.locator('[data-add-version=iba-negroni]').click();await page.locator('#recipe-form [name=name]').fill('我的 3:2:2');await page.locator('#recipe-form [name=author]').fill('Vio');await page.locator('#editor-ingredients [name=amount]').first().fill('45');await page.locator('#recipe-form button[type=submit]').click();await page.waitForSelector('#detail-dialog[open]');let d=await stored();assert.equal(d.recipes.find(r=>r.id==='iba-negroni').versions[0].ingredients[0].amount,'45');assert.match(await page.locator('#detail-dialog').innerText(),/我的 3:2:2/);console.log('PASS ratio version saved');
await page.locator('[data-variant=iba-negroni]').click();assert.equal(await page.locator('.glass-picker .glass-option').count(),await page.evaluate(()=>window.MIX_TAXONOMY.recipe.glasses.length));assert.deepEqual(await page.locator('.glass-picker .glass-option-name').allTextContents(),await page.evaluate(()=>window.MIX_TAXONOMY.recipe.glasses));assert.equal(await page.locator('.glass-picker [name=glasses]:checked').getAttribute('value'),'古典杯');await page.screenshot({path:path.resolve(__dirname,'../../mixbook-glass-picker.png'),fullPage:false});await page.locator('#recipe-form [name=name]').fill('我的尼格罗尼变体');await page.locator('#recipe-form [data-reveal-option=glasses]').click();await page.locator('#recipe-form [data-new-option=glasses]').fill('我的小陶杯');await page.locator('[data-add-option=glasses]').click();await page.locator('#recipe-form [data-reveal-option=tags]').click();await page.locator('#recipe-form [data-new-option=tags]').fill('周末');await page.locator('[data-add-option=tags]').click();await page.locator('#recipe-form [data-reveal-option=sources]').click();await page.locator('#recipe-form [data-new-option=sources]').fill('我的调酒笔记');await page.locator('[data-add-option=sources]').click();assert.equal(await page.locator('[name=sources]:checked').count(),1);await page.locator('#recipe-form [name=source]').fill('第 8 页');await page.locator('#editor-garnishes [data-action=remove-row]').click();await page.locator('#recipe-form button[type=submit]').click();await page.waitForSelector('#detail-dialog[open]');d=await stored();const variant=d.recipes.find(r=>r.name==='我的尼格罗尼变体');assert.equal(variant.parentId,'iba-negroni');assert.equal(variant.glass,'我的小陶杯');assert.ok(variant.tags.includes('周末'));assert.equal(variant.garnishes.length,0);assert.equal(variant.sourceName,'我的调酒笔记');assert.equal(variant.source,'第 8 页');assert.ok(d.options.sources.includes('我的调酒笔记'));assert.equal(await page.locator('.recipe-source').innerText(),'来源：我的调酒笔记');assert.ok(d.options.tags.includes('周末'));console.log('PASS variant, custom chips and empty garnish');
await page.locator('[data-close=detail-dialog]').click();await go('pantry');await page.locator('[data-action=pantry-edit]').click();await page.locator('[data-material-new=product]').click();await page.locator('#item-form [name=name]').fill('自选杜林测试');await page.locator('#item-form [name=parentId]').selectOption('vermouth');await page.locator('#item-form [name=brand]').fill('Dolin');await page.locator('#item-form button[type=submit]').click();await page.waitForSelector('#item-dialog:not([open])',{state:'attached'});await page.locator('[data-action=pantry-save]').click();d=await stored();const product=d.ingredients.find(i=>i.name==='自选杜林测试');assert.equal(product.kind,'product');assert.equal(product.parentId,'vermouth');assert.equal(hasStock(d,product.id),true);await page.locator('[data-action=pantry-cancel]').click();console.log('PASS new brand stored with pantry');
await require('./materials.browser.cjs')({page,stored,go,stock});
await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result)}),saved=await new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>res(r.result)}),products=[{id:'test-jamaican-dark',name:'测试牙买加深色朗姆',tags:['jamaican-rum','dark-rum']},{id:'test-jamaican-light',name:'测试牙买加朗姆',tags:['jamaican-rum']},{id:'test-dark-rum',name:'测试深色朗姆',tags:['dark-rum']}];for(const p of products){saved.data.ingredients.push({...p,kind:'product',category:'基酒',parentId:'rum-all',brand:'Test',aliases:[],image:'',matchParent:true,customized:true});saved.data.pantryItems.push({id:'pantry-'+p.id,name:p.name,brand:'Test',category:'基酒',image:'',matches:[p.id],tags:p.tags})}await new Promise(res=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(saved,'current');tx.oncomplete=res});db.close()});
await page.reload();await page.waitForSelector('.recipe-card');await go('pantry');await page.locator('[data-pantry-section="rum-all"]').click();await page.locator('[data-pantry-tag="jamaican-rum"]').click();assert.equal(await page.locator('.bottle-card').count(),2);await page.locator('[data-pantry-tag="dark-rum"]').click();assert.equal(await page.locator('.bottle-card').count(),1);assert.match(await page.locator('.bottle-card').innerText(),/测试牙买加深色朗姆/);assert.equal(await page.locator('[data-pantry-tag][aria-pressed="true"]').count(),2);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-pantry-tag-filter.png'),fullPage:false});console.log('PASS pantry tags are clickable and multiple selections use AND filtering');
await page.setViewportSize({width:390,height:844});await go('recipes');await page.locator('#recipe-search').fill('');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-mobile.png'),fullPage:false});
await go('settings');await page.locator('[data-action=open-sync-settings]').click();assert.equal(await page.evaluate(()=>{const d=document.querySelector('#sync-dialog'),r=d.getBoundingClientRect();return d.scrollWidth<=d.clientWidth+1&&r.left>=0&&r.right<=innerWidth}),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-sync-mobile.png'),fullPage:false});await page.locator('#sync-dialog [aria-label="关闭同步设置"]').click();await go('recipes');console.log('PASS mobile sync settings modal');
await page.locator('#recipe-search').fill('Negroni');await page.locator('[data-detail=iba-negroni].card-main').click();await page.locator('[data-edit=iba-negroni]').click();assert.equal(await page.evaluate(()=>{const d=document.querySelector('#editor-dialog');return d.scrollWidth<=d.clientWidth+1}),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-editor.png'),fullPage:false});console.log('PASS mobile layout 390px and editor');
await page.locator('#editor-dialog [data-close]').first().click();await page.locator('#confirm-dialog [data-choice=yes]').click();await go('settings');
assert.equal(await page.locator('.connection-icon').evaluate(el=>getComputedStyle(el).display),'grid');console.log('PASS repository icon keeps its centered grid layout');
const vm=require('node:vm'),legacyContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data/legacy-seed.js'),'utf8'),legacyContext);let remote=JSON.parse(JSON.stringify(legacyContext.window.MIX_SEED));remote.pantry.gin=true;remote.favorites.negroni=true;let puts=0,apiCalls=0,apiDelay=0,failPut=false,sha='original-sha';
await context.route('https://api.github.com/**',async route=>{apiCalls++;if(apiDelay)await new Promise(resolve=>setTimeout(resolve,apiDelay));const req=route.request(),url=new URL(req.url());let body,status=200;if(url.pathname.includes('/contents/')){if(req.method()==='PUT'){if(failPut){status=409;body={message:'Conflict'}}else{const payload=JSON.parse(req.postData());assert.equal(payload.sha,sha);remote=JSON.parse(Buffer.from(payload.content,'base64').toString('utf8'));sha='updated-sha-'+(++puts);body={content:{sha}}}}else{const raw=JSON.stringify(remote);body={type:'file',encoding:'base64',size:Buffer.byteLength(raw),sha,content:Buffer.from(raw).toString('base64')}}}else if(url.pathname.includes('/branches/'))body={name:'main'};else body={private:true,default_branch:'main'};await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})});
assert.equal(await page.locator('#sync-dialog[open]').count(),0);await page.locator('[data-action=open-sync-settings]').click();assert.equal(await page.locator('#sync-dialog[open]').count(),1);await page.locator('#sync-form [name=owner]').fill('test-owner');await page.locator('#sync-form [name=repo]').fill('private-test');await page.locator('#sync-form [name=token]').fill('dummy-test-token');await page.locator('#sync-form [name=auto]').check();await page.locator('#sync-form button[type=submit]').click();await page.locator('#confirm-dialog [data-choice=remote]').click();await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');assert.equal(puts,1);assert.equal(remote.schemaVersion,4);assert.equal(hasStock(remote,'gin'),true);assert.equal(remote.favorites['iba-negroni'],true);assert.equal(remote.recipes.filter(r=>r.catalog).length,102);assert.equal(remote.recipes.filter(r=>r.sourceName==='IBA · 难忘经典').length,34);assert.ok(!JSON.stringify(remote).includes('dummy-test-token'));console.log('PASS mocked GitHub v1 migration, guarded PUT, token exclusion');
apiDelay=150;await page.locator('[data-action=sync-now]').click();assert.match(await page.locator('#confirm-dialog').innerText(),/上传本机到仓库.*从仓库下载到本机/s);await page.locator('#confirm-dialog [data-choice=download]').click();await page.locator('#sync-overlay:not([hidden])').waitFor();assert.equal(await page.locator('#sync-overlay').getAttribute('aria-hidden'),'false');await page.screenshot({path:path.resolve(__dirname,'../../mixbook-sync-overlay.png'),fullPage:false});await page.locator('#sync-overlay[hidden]').waitFor({state:'attached'});assert.equal(await page.locator('#sync-overlay').getAttribute('aria-hidden'),'true');apiDelay=0;console.log('PASS manual sync asks for direction and download does not upload');
failPut=true;await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result)}),saved=await new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>res(r.result)});saved.data.favorites['iba-alexander']=true;await new Promise(res=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(saved,'current');tx.oncomplete=res});db.close()});await page.reload();await page.waitForSelector('.recipe-card');await go('settings');await page.locator('[data-action=sync-now]').click();await page.locator('#confirm-dialog [data-choice=upload]').click();await page.locator('.sync-overlay-card[data-sync-state=error]').waitFor();assert.equal(await page.locator('[data-action=retry-sync]').innerText(),'再次同步');assert.equal(await page.locator('[data-action=cancel-sync-result]').innerText(),'取消');failPut=false;await page.locator('[data-action=retry-sync]').click();await page.locator('#confirm-dialog [data-choice=upload]').click();await page.locator('.sync-overlay-card[data-sync-state=success]').waitFor();await page.locator('#sync-overlay[hidden]').waitFor({state:'attached'});console.log('PASS failed manual upload stays open and retry completes successfully');
await page.locator('[data-action=open-sync-settings]').click();await page.locator('#sync-form [name=auto]').uncheck();let toggleCalls=apiCalls;await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(250);assert.ok(apiCalls>toggleCalls);assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('mixbook.config'))).auto,true);toggleCalls=apiCalls;await page.locator('#sync-form button[type=submit]').click();assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('mixbook.config'))).auto,false);assert.match(await page.locator('.connection-summary').innerText(),/自动同步已关闭/);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(250);assert.equal(apiCalls,toggleCalls);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-sync-toggle.png'),fullPage:false});await page.locator('[data-action=open-sync-settings]').click();await page.locator('#sync-form [name=auto]').check();await page.locator('#sync-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('mixbook.config'))).auto,true);assert.match(await page.locator('.connection-summary').innerText(),/自动同步已开启/);console.log('PASS auto-sync toggle only takes effect after saving');
await go('pantry');await page.locator('[data-action=pantry-edit]').click();await stock('campari');const beforeCalls=apiCalls;await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(200);assert.equal(apiCalls,beforeCalls);assert.equal(hasStock(remote,'campari'),false);await page.locator('[data-action=pantry-save]').click();await page.waitForTimeout(2200);await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');assert.equal(hasStock(remote,'campari'),true);const pantryPuts=puts;assert.ok(pantryPuts>=2);console.log('PASS pantry draft pauses sync, save syncs once');
failPut=true;await stock('smirnoff');await page.locator('[data-action=pantry-save]').click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('云端刚发生'));assert.equal(hasStock(await stored(),'smirnoff'),true);assert.equal(hasStock(remote,'smirnoff'),false);assert.equal(puts,pantryPuts);console.log('PASS 409 retains local changes and does not overwrite remote');
await page.locator('[data-action=pantry-cancel]').click();failPut=false;await go('recipes');await page.locator('#recipe-search').fill('Negroni');await page.locator('[data-detail=iba-negroni].card-main').click();await page.locator('[data-add-version=iba-negroni]').click();await page.locator('#recipe-form [name=name]').fill('同步替代品测试');
const firstRow=()=>page.locator('#editor-ingredients .ingredient-edit-row').first();
await firstRow().locator('[data-choose-material]').click();await page.locator('#material-dialog [data-material-search]').fill('拉弗格');await page.locator('#material-dialog [data-material-select=laphroaig-10]').click();
assert.equal(await firstRow().locator('[data-add-alternative]').count(),0);
await page.locator('#recipe-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');
assert.equal(remote.schemaVersion,4);assert.equal(remote.ingredients.find(i=>i.id==='sloe-gin').matchParent,false);assert.deepEqual(remote.recipes.find(r=>r.id==='iba-negroni').versions.find(v=>v.name==='同步替代品测试').ingredients[0].alternatives,[]);assert.equal(hasStock(remote,'smirnoff'),true);assert.equal(puts,pantryPuts+1);console.log('PASS recipe version without substitution control and matching boundary survive mocked cloud sync');
await page.goto(base+'photo-map.html');if(fs.existsSync(qaFont))await page.addStyleTag({content:'@font-face{font-family:"PingFang SC";src:url(data:font/otf;base64,'+fs.readFileSync(qaFont).toString('base64')+');font-weight:100 900}'});await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('figure').count(),58);await page.locator('figure img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode()})));assert.equal(await page.locator('figure .note').count(),5);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-photo-map-mobile.png'),fullPage:false});console.log('PASS photo map: 58 images, 5 appearance notes, mobile layout');
assert.deepEqual(errors,[]);console.log('PASS no browser runtime errors');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
