/* Run with TEST_NODE_MODULES pointing to test dependencies, plus a local HTTP server. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const deps=process.env.TEST_NODE_MODULES||path.resolve(__dirname,'../../testdeps/node_modules');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[path.extname(p)]||'application/json');res.end(fs.readFileSync(p))}catch{res.writeHead(404).end()}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||path.resolve(deps,'../chromium'),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:'+server.address().port+'/';
const qaFont=path.resolve(deps,'../qa-cjk.otf');if(fs.existsSync(qaFont))await context.route('**/styles.css',route=>route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(root,'styles.css'),'utf8')+'\n@font-face{font-family:"PingFang SC";src:url(data:font/otf;base64,'+fs.readFileSync(qaFont).toString('base64')+');font-weight:100 900;font-style:normal}'}));
async function stored(){return page.evaluate(async()=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>{db.close();res(r.result.data)}})})}
async function go(view){await page.locator(`.nav [data-view=${view}]`).click()}
try{
await page.goto(base);await page.waitForSelector('.recipe-card');assert.equal(await page.locator('.recipe-card').count(),102);assert.equal((await stored()).schemaVersion,2);console.log('PASS initial 102 recipes persisted');
await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-desktop.png'),fullPage:false});
assert.equal(await page.locator('[data-filter=formats],[data-filter=families],[data-filter=bases],#iba-filter,#method-filter').count(),0);
await page.locator('#source-filter').selectOption('IBA · 当代经典');assert.equal(await page.locator('.recipe-card').count(),34);await page.locator('[data-filter=tags][data-value="酸甜"]').click();assert.ok(await page.locator('.recipe-card').count()>0);assert.ok((await page.locator('.card-no').allTextContents()).every(x=>x.includes('IBA · 当代经典')));assert.ok((await page.locator('.card-tags').allTextContents()).every(x=>x.includes('酸甜')));await page.locator('[data-action=reset-filters]').click();console.log('PASS flavor and single source filters; old classifications absent');
// Simulate an existing v2 browser record and reload through the actual migration path.
await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('mixbook',1);r.onsuccess=()=>res(r.result)});const saved=await new Promise(res=>{const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>res(r.result)});saved.data.catalogVersion='iba-2026-09-21-v2';for(const r of saved.data.recipes){r.ibaCategory=r.sourceName.replace('IBA · ','');delete r.sourceName;r.formats=['短饮'];r.families=['Tiki']}saved.data.recipes[0].notes='升级保留我的笔记';await new Promise(res=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(saved,'current');tx.oncomplete=res});db.close()});await page.reload();await page.waitForSelector('.recipe-card');assert.equal((await stored()).recipes[0].notes,'升级保留我的笔记');assert.equal((await stored()).recipes[0].sourceName,'IBA · 难忘经典');assert.equal((await stored()).recipes[0].families,undefined);console.log('PASS existing v2 browser upgrade');
await go('pantry');assert.equal(await page.locator('[data-pantry]').count(),0);await page.locator('[data-action=pantry-edit]').click();await page.locator('[data-pantry=gin]').check();assert.equal((await stored()).pantry.gin,undefined);await page.locator('[data-action=pantry-cancel]').click();assert.equal((await stored()).pantry.gin,undefined);console.log('PASS pantry cancellation does not persist');
await page.locator('[data-action=pantry-edit]').click();for(const id of ['gin','campari','dolin-rouge'])await page.locator(`[data-pantry=${id}]`).check();await page.locator('[data-action=pantry-save]').click();await page.waitForSelector('[data-action=pantry-edit]');assert.equal(await page.locator('.bottle-card').count(),3);await page.reload();await page.waitForSelector('.recipe-card');assert.equal((await stored()).pantry['dolin-rouge'],true);console.log('PASS pantry save and reload');
await page.locator('#recipe-search').fill('Negroni');await page.locator('[data-detail=iba-negroni].card-main').click();assert.match(await page.locator('#detail-dialog').innerText(),/材料齐全/);assert.equal(await page.locator('.recipe-source').innerText(),'来源：IBA · 难忘经典');assert.match(await page.locator('#detail-dialog').innerText(),/酒柜：杜林/);
await page.locator('[data-add-version=iba-negroni]').click();await page.locator('#recipe-form [name=name]').fill('我的 3:2:2');await page.locator('#recipe-form [name=author]').fill('Vio');await page.locator('#editor-ingredients [name=amount]').first().fill('45');await page.locator('#recipe-form button[type=submit]').click();await page.waitForSelector('#detail-dialog[open]');let d=await stored();assert.equal(d.recipes.find(r=>r.id==='iba-negroni').versions[0].ingredients[0].amount,'45');assert.match(await page.locator('#detail-dialog').innerText(),/我的 3:2:2/);console.log('PASS ratio version saved');
await page.locator('[data-variant=iba-negroni]').click();await page.locator('#recipe-form [name=name]').fill('我的尼格罗尼变体');await page.locator('#recipe-form [data-new-option=glasses]').fill('我的小陶杯');await page.locator('[data-add-option=glasses]').click();await page.locator('#recipe-form [data-new-option=tags]').fill('周末');await page.locator('[data-add-option=tags]').click();await page.locator('#recipe-form [data-new-option=sources]').fill('我的调酒笔记');await page.locator('[data-add-option=sources]').click();assert.equal(await page.locator('[name=sources]:checked').count(),1);await page.locator('#recipe-form [name=source]').fill('第 8 页');await page.locator('#editor-garnishes [data-action=remove-row]').click();await page.locator('#recipe-form button[type=submit]').click();await page.waitForSelector('#detail-dialog[open]');d=await stored();const variant=d.recipes.find(r=>r.name==='我的尼格罗尼变体');assert.equal(variant.parentId,'iba-negroni');assert.equal(variant.glass,'我的小陶杯');assert.ok(variant.tags.includes('周末'));assert.equal(variant.garnishes.length,0);assert.equal(variant.sourceName,'我的调酒笔记');assert.equal(variant.source,'第 8 页');assert.ok(d.options.sources.includes('我的调酒笔记'));assert.equal(await page.locator('.recipe-source').innerText(),'来源：我的调酒笔记');assert.ok(d.options.tags.includes('周末'));console.log('PASS variant, custom chips and empty garnish');
await page.locator('[data-close=detail-dialog]').click();await go('pantry');await page.locator('[data-action=pantry-edit]').click();await page.locator('[data-action=new-pantry-item]').click();await page.locator('#item-form [name=name]').fill('自选杜林测试');await page.locator('#item-form [name=parentId]').selectOption('vermouth');await page.locator('#item-form [name=brand]').fill('Dolin');await page.locator('#item-form button[type=submit]').click();await page.waitForSelector('#item-dialog:not([open])',{state:'attached'});await page.locator('[data-action=pantry-save]').click();await page.waitForSelector('[data-action=pantry-edit]');d=await stored();const product=d.ingredients.find(i=>i.name==='自选杜林测试');assert.equal(product.kind,'product');assert.equal(product.parentId,'vermouth');assert.equal(d.pantry[product.id],true);console.log('PASS new brand stored with pantry');
await page.setViewportSize({width:390,height:844});await go('recipes');await page.locator('#recipe-search').fill('');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-mobile.png'),fullPage:false});
await page.locator('#recipe-search').fill('Negroni');await page.locator('[data-detail=iba-negroni].card-main').click();await page.locator('[data-edit=iba-negroni]').click();assert.equal(await page.evaluate(()=>{const d=document.querySelector('#editor-dialog');return d.scrollWidth<=d.clientWidth+1}),true);await page.screenshot({path:path.resolve(__dirname,'../../mixbook-editor.png'),fullPage:false});console.log('PASS mobile layout 390px and editor');
await page.locator('#editor-dialog [data-close]').first().click();await page.locator('#confirm-dialog [data-choice=yes]').click();await go('settings');
const vm=require('node:vm'),legacyContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data/legacy-seed.js'),'utf8'),legacyContext);let remote=JSON.parse(JSON.stringify(legacyContext.window.MIX_SEED));remote.pantry.gin=true;remote.favorites.negroni=true;let puts=0,apiCalls=0,failPut=false,sha='original-sha';
await context.route('https://api.github.com/**',async route=>{apiCalls++;const req=route.request(),url=new URL(req.url());let body,status=200;if(url.pathname.includes('/contents/')){if(req.method()==='PUT'){if(failPut){status=409;body={message:'Conflict'}}else{const payload=JSON.parse(req.postData());assert.equal(payload.sha,sha);remote=JSON.parse(Buffer.from(payload.content,'base64').toString('utf8'));sha='updated-sha-'+(++puts);body={content:{sha}}}}else{const raw=JSON.stringify(remote);body={type:'file',encoding:'base64',size:Buffer.byteLength(raw),sha,content:Buffer.from(raw).toString('base64')}}}else if(url.pathname.includes('/branches/'))body={name:'main'};else body={private:true,default_branch:'main'};await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})});
await page.locator('#sync-form [name=owner]').fill('test-owner');await page.locator('#sync-form [name=repo]').fill('private-test');await page.locator('#sync-form [name=token]').fill('dummy-test-token');await page.locator('#sync-form [name=auto]').check();await page.locator('#sync-form button[type=submit]').click();await page.locator('#confirm-dialog [data-choice=remote]').click();await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');assert.equal(puts,1);assert.equal(remote.schemaVersion,2);assert.equal(remote.pantry.gin,true);assert.equal(remote.favorites['iba-negroni'],true);assert.equal(remote.recipes.filter(r=>r.catalog).length,102);assert.equal(remote.recipes.filter(r=>r.sourceName==='IBA · 难忘经典').length,34);assert.ok(!JSON.stringify(remote).includes('dummy-test-token'));console.log('PASS mocked GitHub v1 migration, guarded PUT, token exclusion');
await go('pantry');await page.locator('[data-action=pantry-edit]').click();await page.locator('[data-pantry=campari]').check();const beforeCalls=apiCalls;await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(200);assert.equal(apiCalls,beforeCalls);assert.equal(remote.pantry.campari,undefined);await page.locator('[data-action=pantry-save]').click();await page.waitForSelector('[data-action=pantry-edit]');await page.waitForFunction(()=>document.querySelector('.status-text')?.textContent==='已同步');assert.equal(remote.pantry.campari,true);assert.equal(puts,2);console.log('PASS pantry draft pauses sync, save syncs once');
failPut=true;await page.locator('[data-action=pantry-edit]').click();await page.locator('[data-pantry=vodka]').check();await page.locator('[data-action=pantry-save]').click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('云端刚发生'));assert.equal((await stored()).pantry.vodka,true);assert.equal(remote.pantry.vodka,undefined);assert.equal(puts,2);console.log('PASS 409 retains local changes and does not overwrite remote');
assert.deepEqual(errors,[]);console.log('PASS no browser runtime errors');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
