const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),C=require('../core.js');
const root=path.join(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'seed.js'),'utf8'),ctx);const seed=C.validate(C.clone(ctx.window.MIX_SEED));const data=()=>C.clone(seed),recipe=(d,id)=>d.recipes.find(r=>r.id==='iba-'+id);
function legacy(){const x={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data/legacy-seed.js'),'utf8'),x);return x.window.MIX_SEED}
test('102 条 IBA 配方都有独立来源，三组各 34 条，引用完整',()=>{assert.equal(seed.recipes.length,102);assert.equal(new Set(seed.recipes.map(r=>r.source)).size,102);const sources=JSON.parse(fs.readFileSync(path.join(root,'data/sources.json')));assert.deepEqual(seed.recipes.map(r=>r.source).sort(),sources.recipes.map(r=>r.url).sort());for(const category of ['难忘经典','当代经典','新时代'])assert.equal(seed.recipes.filter(r=>r.sourceName==='IBA · '+category).length,34);C.validate(seed)});
test('所有引用的图片实际存在，未完成的图片为空',()=>{for(const r of seed.recipes)if(r.image)assert.ok(fs.existsSync(path.join(root,r.image==='negroni'?'assets/negroni.webp':`assets/cocktails/${r.image}.webp`)));for(const i of seed.ingredients)if(i.image)assert.ok(fs.existsSync(path.join(root,`assets/ingredients/${i.image}.webp`)))});
test('杜林和马天尼满足甜红味美思，反向和同类品牌不等价',()=>{const d=data();for(const i of ['dolin-rouge','martini-rosso'])assert.ok(C.satisfies(i,'vermouth',d));assert.equal(C.satisfies('vermouth','dolin-rouge',d),false);assert.equal(C.satisfies('dolin-rouge','cinzano-rosso',d),false)});
test('君度满足 Triple Sec，但蓝橙与君度不可互换',()=>{const d=data();assert.ok(C.satisfies('cointreau','triple-sec',d));assert.ok(C.satisfies('bols-blue','orange-liqueur',d));assert.equal(C.satisfies('bols-blue','cointreau',d),false);assert.equal(C.satisfies('triple-sec','cointreau',d),false);assert.equal(C.satisfies('curacao','triple-sec',d),false)});
test('两种苦精不会误匹配',()=>{const d=data();assert.equal(C.satisfies('angostura','peychauds',d),false);assert.equal(C.satisfies('peychauds','angostura',d),false);assert.ok(C.satisfies('angostura','aromatic-bitters',d))});
test('酒柜产品匹配基础配方且不要求装饰',()=>{const d=data();d.pantry={gin:true,campari:true,'dolin-rouge':true};const m=C.match(recipe(d,'negroni'),d);assert.ok(m.ready);assert.equal(m.garnishes.length,1);assert.equal(m.total,3)});
test('指定产品配方严格匹配',()=>{const d=data(),r=recipe(d,'rabo-de-galo');d.pantry={cachaca:true,vermouth:true,cynar:true};assert.equal(C.match(r,d).missing[0].id,'cinzano-rosso');d.pantry['cinzano-rosso']=true;assert.ok(C.match(r,d).ready)});
test('明确列出的替代品可用，蛋清的可选性保留',()=>{const d=data();d.pantry={rye:true,campari:true,vermouth:true};assert.ok(C.match(recipe(d,'boulevardier'),d).ready);d.pantry={bourbon:true,lemon:true,syrup:true};assert.ok(C.match(recipe(d,'whiskey-sour'),d).ready);assert.equal(recipe(d,'new-york-sour').ingredients.find(i=>i.id==='egg-white').optional,false)});
test('维持官网容易误记的配方量与指定品牌',()=>{const d=data();assert.equal(recipe(d,'monkey-gland').ingredients.find(x=>x.id==='absinthe').unit,'汤匙');assert.equal(recipe(d,'bees-knees').ingredients.find(x=>x.id==='orange-juice').amount,'22.5');assert.equal(recipe(d,'vieux-carre').ingredients.at(-1).id,'peychauds');assert.equal(recipe(d,'moscow-mule').ingredients[0].id,'smirnoff');assert.equal(recipe(d,'sazerac').ingredients[0].id,'cognac')});
test('搜索支持关键词、风味和单一来源交叉筛选',()=>{const d=data();assert.ok(C.query(d,{q:'Negroni'}).some(r=>r.id==='iba-negroni'));const result=C.query(d,{tags:['酸甜','苦甜'],sourceName:'IBA · 难忘经典'});assert.ok(result.length>0);assert.ok(result.every(r=>r.sourceName==='IBA · 难忘经典'&&r.tags.some(t=>['酸甜','苦甜'].includes(t))));assert.equal(C.query(d,{q:'君度',sourceName:'IBA · 当代经典'}).some(r=>r.id==='iba-cosmopolitan'),true);assert.equal(C.query(d,{q:'IBA 新时代'}).length,34)});
test('v1 迁移保留酒柜和收藏，拆分装饰',()=>{const old=legacy();old.pantry.gin=true;old.favorites.negroni=true;const d=C.installCatalog(old,seed);assert.equal(d.schemaVersion,2);assert.equal(d.pantry.gin,true);assert.equal(d.favorites['iba-negroni'],true);assert.equal(d.recipes.filter(r=>r.catalog).length,102);assert.equal(C.validate(old).recipes.find(r=>r.id==='negroni').garnishes[0].id,'orange')});
test('目录升级不覆盖用户编辑，删除后重启不自动恢复',()=>{const old=legacy();old.recipes[0].sample=false;old.recipes[0].notes='我的笔记';const d=C.installCatalog(old,seed);assert.equal(d.recipes.find(r=>r.id==='negroni').notes,'我的笔记');assert.deepEqual(C.installCatalog(d,seed),d);d.recipes=d.recipes.filter(r=>r.id!=='iba-alexander');assert.equal(C.installCatalog(d,seed).recipes.some(r=>r.id==='iba-alexander'),false)});
test('比例版本与本体变体可完整保存',()=>{const d=data(),r=recipe(d,'negroni');r.versions=[{id:'my-ratio',name:'我的 3:2:2',author:'自己',notes:'',steps:r.steps,ingredients:r.ingredients.map((i,n)=>({...i,amount:n?'30':'45'})),garnishes:[]}];const normalized=C.validate(d);assert.equal(recipe(normalized,'boulevardier').parentId,r.id);assert.equal(recipe(normalized,'negroni').versions[0].ingredients[0].amount,'45')});
test('两个设备的独立酒柜改动可合并',()=>{const b=data(),l=data(),r=data();l.pantry.gin=true;r.pantry.campari=true;const m=C.merge(b,l,r);assert.deepEqual(m.conflicts,[]);assert.deepEqual(m.data.pantry,{gin:true,campari:true})});
test('并发编辑同一配方会报告冲突，不能静默覆盖',()=>{const b=data(),l=data(),r=data();l.recipes[0].notes='甲';r.recipes[0].notes='乙';const m=C.merge(b,l,r);assert.deepEqual(m.conflicts,['recipes:iba-alexander'])});
test('删除与编辑冲突，独立配方改动不冲突',()=>{const b=data(),l=data(),r=data();l.recipes=l.recipes.filter(x=>x.id!=='iba-alexander');r.recipes[0].notes='远端笔记';r.recipes[1].notes='另一杯';const m=C.merge(b,l,r);assert.ok(m.conflicts.includes('recipes:iba-alexander'));assert.equal(m.data.recipes.find(x=>x.id==='iba-americano').notes,'另一杯')});
test('材料与配方关联都拒绝循环和悬空关系',()=>{let d=data();d.ingredients.find(i=>i.id==='gin').parentId='london-dry';assert.throws(()=>C.validate(d),/循环/);d=data();recipe(d,'negroni').parentId='iba-boulevardier';assert.throws(()=>C.validate(d),/循环/);d=data();d.recipes[0].ingredients[0].id='missing';assert.throws(()=>C.validate(d),/引用/) });
test('导入数据拒绝危险编号、路径和未来版本，凭据不进入导出',()=>{let d=data();d.ingredients[0].id='__proto__';assert.throws(()=>C.validate(d));d=data();d.recipes[0].image='../../anything';assert.throws(()=>C.validate(d));d=data();d.schemaVersion=99;assert.throws(()=>C.validate(d));d=data();d.token='secret';assert.equal(C.validate(d).token,undefined)});

test('旧 v2 来源迁移保留个人内容和删除记录，不引入重复分类',()=>{
 const old=data();old.catalogVersion='iba-2026-09-21-v2';old.options.formats=['短饮'];old.options.families=['Tiki'];delete old.options.sources;
 for(const r of old.recipes){r.ibaCategory=r.sourceName.replace('IBA · ','');delete r.sourceName;r.formats=['短饮'];r.families=['Tiki']}
 old.recipes=old.recipes.filter(r=>r.id!=='iba-alexander');const r=recipe(old,'negroni');r.notes='保留笔记';r.ingredients[0].amount='45';r.customized=true;r.versions=[{id:'ratio',name:'比例',author:'Vio',notes:'偏好',ingredients:r.ingredients,garnishes:[],steps:r.steps}];old.pantry.gin=true;old.favorites[r.id]=true;
 const d=C.installCatalog(old,seed),n=recipe(d,'negroni');assert.equal(d.recipes.length,101);assert.equal(n.sourceName,'IBA · 难忘经典');assert.equal(n.notes,'保留笔记');assert.equal(n.ingredients[0].amount,'45');assert.deepEqual(n.versions,r.versions);assert.equal(d.pantry.gin,true);assert.equal(d.favorites[r.id],true);assert.equal(n.formats,undefined);assert.equal(n.families,undefined);assert.equal(n.ibaCategory,undefined);assert.deepEqual(Object.keys(d.options).sort(),['glasses','sources','tags']);assert.deepEqual(C.installCatalog(d,seed),d);
});
test('自定义来源与链接独立保存、可留空、跨设备合并',()=>{const b=data(),l=data(),r=data();l.options.sources.push('调酒笔记');l.recipes[0].sourceName='调酒笔记';l.recipes[0].source='第 12 页';r.options.sources.push('朋友的配方');const merged=C.merge(b,l,r);assert.deepEqual(merged.conflicts,[]);const d=C.validate(merged.data);assert.equal(d.recipes[0].sourceName,'调酒笔记');assert.equal(d.recipes[0].source,'第 12 页');assert.ok(d.options.sources.includes('朋友的配方'));d.recipes[0].sourceName='';assert.equal(C.validate(d).recipes[0].sourceName,'')});
test('来源升级与云端独立笔记修改合并不会制造冲突',()=>{const b=data();b.catalogVersion='iba-2026-09-21-v2';for(const r of b.recipes){r.ibaCategory=r.sourceName.replace('IBA · ','');delete r.sourceName;r.formats=['短饮'];r.families=['经典']}const remote=C.clone(b);remote.recipes[0].notes='云端新增笔记';const upgraded=C.installCatalog(b,seed);const m=C.merge(upgraded,upgraded,C.installCatalog(remote,seed));assert.deepEqual(m.conflicts,[]);assert.equal(m.data.recipes[0].notes,'云端新增笔记')});
