const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core.js');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../seed.js'),'utf8'),ctx);
const catalog=C.clone(ctx.window.MIX_SEED),data=()=>C.validate(C.clone(catalog)),row=(id,alternatives=[])=>({id,amount:'30',unit:'ml',optional:false,alternatives});
test('v3 材料目录支持任意深度，产品只能挂在类别之下',()=>{const d=data();assert.deepEqual(C.ingredientPath('laphroaig-10',d).map(i=>i.id),['spirit','whiskey','scotch','islay','laphroaig-10']);assert.ok(C.satisfies('laphroaig-10','scotch',d));assert.ok(C.satisfies('laphroaig-10','whiskey',d));assert.equal(C.satisfies('scotch','laphroaig-10',d),false);d.ingredients.find(i=>i.id==='ardbeg-10').parentId='laphroaig-10';assert.throws(()=>C.validate(d),/上级必须/)});
test('黑刺李在金酒目录可见，但不会自动满足普通金酒配方',()=>{const d=data();assert.ok(C.ingredientPath('monkey47-sloe',d).some(i=>i.id==='gin'));assert.ok(C.satisfies('monkey47-sloe','sloe-gin',d));assert.equal(C.satisfies('monkey47-sloe','gin',d),false);assert.equal(C.satisfies('sloe-gin','gin',d),false);assert.ok(C.satisfies('monkey47-dry','gin',d));assert.ok(C.satisfies('beefeater','london-dry',d))});
test('类别要求和产品要求独立，原料可明确允许跨类别替代',()=>{const d=data();d.pantry={'bols-blue':true};assert.ok(C.have(row('orange-liqueur'),d));assert.equal(C.have(row('cointreau'),d),false);assert.ok(C.have(row('cointreau',['bols-blue']),d));d.pantry={'monkey47-sloe':true};assert.ok(C.have(row('gin',['sloe-gin']),d));assert.equal(C.have(row('gin'),d),false)});
test('烟熏配方只接受本行声明的替代品，优先区分原料齐全和替代可做',()=>{const d=data(),r={ingredients:[row('laphroaig-10',['ardbeg-10','lagavulin-16']),row('vermouth'),row('campari')],garnishes:[]};d.pantry={'ardbeg-10':true,'dolin-rouge':true,campari:true};assert.ok(C.match(r,d).ready);assert.equal(C.match(r,d).substitutions[0].id,'laphroaig-10');assert.equal(C.have(row('laphroaig-10'),d),false);d.pantry['laphroaig-10']=true;assert.equal(C.match(r,d).substitutions.length,0)});
test('多个替代品在保存、版本、序列化和合并中完整保留',()=>{const b=data(),l=data(),r=data(),recipe=l.recipes[0];recipe.ingredients=[row('laphroaig-10',['ardbeg-10','lagavulin-16','ardbeg-10'])];recipe.versions=[{id:'alt-version',name:'另一比例',author:'',notes:'',ingredients:[row('campari',['aperol','cynar'])],garnishes:[],steps:['搅拌']}];r.pantry['ardbeg-10']=true;const m=C.merge(b,l,r);assert.deepEqual(m.conflicts,[]);const d=C.validate(JSON.parse(JSON.stringify(m.data)));assert.deepEqual(d.recipes[0].ingredients[0].alternatives,['ardbeg-10','lagavulin-16']);assert.deepEqual(d.recipes[0].versions[0].ingredients[0].alternatives,['aperol','cynar']);assert.equal(d.pantry['ardbeg-10'],true)});
test('独立产品可以没有父类别或品牌属性，具体名称和编号仍可引用',()=>{const d=data();d.ingredients.push({id:'standalone',name:'自制香料酒',kind:'product',category:'其他',parentId:'',brand:'',aliases:[],image:''});d.pantry.standalone=true;const normalized=C.validate(d);assert.ok(C.have(row('standalone'),normalized));assert.equal(C.satisfies('standalone','herbal-liqueur',normalized),false)});
test('酒柜普通材料可直接持有，酒类类别只保留既有未指定记录',()=>{const d=data(),get=id=>d.ingredients.find(i=>i.id===id);for(const id of ['gin','vermouth','bitters','aromatic-bitters','scotch'])assert.equal(C.needsProduct(get(id),d),true,id);for(const id of ['lime','syrup','sugar','campari','angostura'])assert.equal(C.needsProduct(get(id),d),false,id)});
test('好奇美国佬不是红味美思，品牌相同也不能误匹配',()=>{const d=data();assert.equal(C.satisfies('cocchi-americano','vermouth',d),false);assert.ok(C.satisfies('cocchi-storico','vermouth',d));assert.equal(C.satisfies('cocchi-storico','cocchi-americano',d),false)});
test('搜索产品配方也能用其类别和品牌检索',()=>{const d=data();d.recipes[0].ingredients=[row('laphroaig-10',['ardbeg-10'])];assert.ok(C.query(d,{q:'苏格兰 Laphroaig'}).some(r=>r.id===d.recipes[0].id));assert.ok(C.query(d,{q:'阿贝10年'}).some(r=>r.id===d.recipes[0].id));assert.match(C.materialText(d.ingredients.find(i=>i.id==='havana-7'),d),/黑朗姆/)});
test('实际 v2 数据形态迁移保留酒柜、配方与别名，并给旧名称加别名',()=>{const old=data();old.schemaVersion=2;old.catalogVersion='iba-2026-09-21-photos-v4';old.ingredients=old.ingredients.filter(i=>!['dry-gin','sloe-gin','beefeater','monkey47-dry','monkey47-sloe','dark-rum','havana-7','laphroaig-10','ardbeg-10','cocchi-storico','cocchi-americano'].includes(i.id));for(const i of old.ingredients){delete i.matchParent;delete i.customized}old.ingredients.find(i=>i.id==='vermouth').name='甜红味美思';old.ingredients.find(i=>i.id==='orange-liqueur').name='橙味利口酒（大类）';old.pantry={gin:true,'dolin-rouge':true};old.recipes[0].notes='我自己的笔记';old.recipes[0].ingredients[0].amount='42';const before=C.clone(old),up=C.installCatalog(old,catalog);assert.equal(up.schemaVersion,3);assert.deepEqual(up.pantry,before.pantry);assert.deepEqual(up.recipes,before.recipes);assert.equal(up.ingredients.find(i=>i.id==='vermouth').name,'红味美思');assert.ok(up.ingredients.find(i=>i.id==='vermouth').aliases.includes('甜红味美思'));assert.equal(up.ingredients.find(i=>i.id==='sloe-gin').matchParent,false);assert.deepEqual(C.installCatalog(up,catalog),up)});
test('目录升级不覆盖自行修改的材料归类、名称或匹配规则',()=>{const old=data();old.catalogVersion='older';const i=old.ingredients.find(i=>i.id==='vermouth');Object.assign(i,{name:'我的红味美思',parentId:'aromatized-wine',matchParent:false,customized:true});assert.deepEqual(C.installCatalog(old,catalog).ingredients.find(x=>x.id===i.id),i)});
test('替代品引用、循环与匹配规则严格校验',()=>{let d=data();d.recipes[0].ingredients[0].alternatives=['missing'];assert.throws(()=>C.validate(d),/替代/);d=data();d.ingredients.find(i=>i.id==='gin').matchParent='false';assert.throws(()=>C.validate(d),/匹配边界/);d=data();d.ingredients.find(i=>i.id==='sloe-gin').parentId='monkey47-sloe';assert.throws(()=>C.validate(d),/循环|上级必须/)});

test('酒柜基酒入口归并为六类，利口酒分组使用简短名称',()=>{const d=data(),roots=d.ingredients.filter(i=>i.parentId==='spirit');assert.deepEqual(roots.map(i=>i.name),['金酒','朗姆酒','伏特加','威士忌','龙舌兰','白兰地']);assert.equal(d.ingredients.find(i=>i.id==='mezcal').parentId,'tequila');assert.equal(d.ingredients.find(i=>i.id==='cachaca').parentId,'rum-all');assert.ok(d.ingredients.filter(i=>i.category==='利口酒').length>0);assert.equal(d.ingredients.some(i=>i.category==='利口酒与味美思'),false)});
