const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core.js');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../seed.js'),'utf8'),ctx);
const catalog=C.clone(ctx.window.MIX_SEED),data=()=>C.validate(C.clone(catalog)),row=(id,alternatives=[])=>({id,amount:'30',unit:'ml',optional:false,alternatives});
const own=(d,...ids)=>{d.pantryItems=ids.map((id,n)=>{const i=d.ingredients.find(x=>x.id===id);return{id:`owned-${id}-${n}`,name:i.name,brand:i.brand||'',category:i.category,image:i.image||'',matches:[id],tags:[...(i.tags||[])]}})};
test('材料目录支持酒精抽屉、类别、标签和产品层级',()=>{const d=data();assert.deepEqual(C.ingredientPath('laphroaig-10',d).map(i=>i.id),['alcohol','whiskey','islay','laphroaig-10']);assert.ok(C.satisfies('laphroaig-10','scotch',d));assert.ok(C.satisfies('laphroaig-10','whiskey',d));assert.equal(C.satisfies('scotch','laphroaig-10',d),false);d.ingredients.find(i=>i.id==='ardbeg-10').parentId='laphroaig-10';assert.throws(()=>C.validate(d),/上级必须/)});
test('黑刺李在金酒目录可见，但不会自动满足普通金酒配方',()=>{const d=data();assert.ok(C.ingredientPath('monkey47-sloe',d).some(i=>i.id==='gin'));assert.ok(C.satisfies('monkey47-sloe','sloe-gin',d));assert.equal(C.satisfies('monkey47-sloe','gin',d),false);assert.equal(C.satisfies('sloe-gin','gin',d),false);assert.ok(C.satisfies('monkey47-dry','gin',d));assert.ok(C.satisfies('beefeater','london-dry',d))});
test('类别要求和产品要求独立，原料可明确允许跨类别替代',()=>{const d=data();own(d,'bols-blue');assert.ok(C.have(row('orange-liqueur'),d));assert.equal(C.have(row('cointreau'),d),false);assert.ok(C.have(row('cointreau',['bols-blue']),d));own(d,'monkey47-sloe');assert.ok(C.have(row('gin',['sloe-gin']),d));assert.equal(C.have(row('gin'),d),false)});
test('烟熏配方只接受本行声明的替代品，优先区分原料齐全和替代可做',()=>{const d=data(),r={ingredients:[row('laphroaig-10',['ardbeg-10','lagavulin-16']),row('vermouth'),row('campari')],garnishes:[]};own(d,'ardbeg-10','dolin-rouge','campari');assert.ok(C.match(r,d).ready);assert.equal(C.match(r,d).substitutions[0].id,'laphroaig-10');assert.equal(C.have(row('laphroaig-10'),d),false);own(d,'ardbeg-10','dolin-rouge','campari','laphroaig-10');assert.equal(C.match(r,d).substitutions.length,0)});
test('多个替代品在保存、版本、序列化和合并中完整保留',()=>{const b=data(),l=data(),r=data(),recipe=l.recipes[0];recipe.ingredients=[row('laphroaig-10',['ardbeg-10','lagavulin-16','ardbeg-10'])];recipe.versions=[{id:'alt-version',name:'另一比例',author:'',notes:'',ingredients:[row('campari',['aperol','cynar'])],garnishes:[],steps:['搅拌']}];own(r,'ardbeg-10');const m=C.merge(b,l,r);assert.deepEqual(m.conflicts,[]);const d=C.validate(JSON.parse(JSON.stringify(m.data)));assert.deepEqual(d.recipes[0].ingredients[0].alternatives,['ardbeg-10','lagavulin-16']);assert.deepEqual(d.recipes[0].versions[0].ingredients[0].alternatives,['aperol','cynar']);assert.ok(d.pantryItems.some(i=>i.matches.includes('ardbeg-10')))});
test('独立产品可以没有父类别或品牌属性，具体名称和编号仍可引用',()=>{const d=data();d.ingredients.push({id:'standalone',name:'自制香料酒',kind:'product',category:'其他',parentId:'',brand:'',aliases:[],image:''});own(d,'standalone');const normalized=C.validate(d);assert.ok(C.have(row('standalone'),normalized));assert.equal(C.satisfies('standalone','herbal-liqueur',normalized),false)});
test('酒柜普通材料可直接持有，酒类类别只保留既有未指定记录',()=>{const d=data(),get=id=>d.ingredients.find(i=>i.id===id);for(const id of ['gin','vermouth','bitters','aromatic-bitters','scotch'])assert.equal(C.needsProduct(get(id),d),true,id);for(const id of ['lime','syrup','sugar','campari','angostura'])assert.equal(C.needsProduct(get(id),d),false,id)});
test('好奇美国佬不是红味美思，品牌相同也不能误匹配',()=>{const d=data();assert.equal(C.satisfies('cocchi-americano','vermouth',d),false);assert.ok(C.satisfies('cocchi-storico','vermouth',d));assert.equal(C.satisfies('cocchi-storico','cocchi-americano',d),false)});
test('搜索产品配方也能用其标签和品牌检索',()=>{const d=data();d.recipes[0].ingredients=[row('laphroaig-10',['ardbeg-10'])];assert.ok(C.query(d,{q:'苏格兰 Laphroaig'}).some(r=>r.id===d.recipes[0].id));assert.ok(C.query(d,{q:'阿贝10年'}).some(r=>r.id===d.recipes[0].id));assert.match(C.materialText(d.ingredients.find(i=>i.id==='havana-7'),d),/黑朗姆/)});
test('实际 v2 数据形态迁移保留酒柜、配方与别名，并给旧名称加别名',()=>{const old=data();old.schemaVersion=2;old.catalogVersion='iba-2026-09-21-photos-v4';old.ingredients=old.ingredients.filter(i=>!['dry-gin','sloe-gin','beefeater','monkey47-dry','monkey47-sloe','dark-rum','havana-7','laphroaig-10','ardbeg-10','cocchi-storico','cocchi-americano'].includes(i.id));for(const i of old.ingredients){delete i.matchParent;delete i.customized}old.ingredients.find(i=>i.id==='vermouth').name='甜红味美思';old.ingredients.find(i=>i.id==='orange-liqueur').name='橙味利口酒（大类）';old.pantry={gin:true,'dolin-rouge':true};old.recipes[0].notes='我自己的笔记';old.recipes[0].ingredients[0].amount='42';const before=C.clone(old),up=C.installCatalog(old,catalog);assert.equal(up.schemaVersion,4);assert.deepEqual(up.pantryItems.map(i=>i.matches[0]).sort(),Object.keys(before.pantry).sort());assert.deepEqual(up.recipes,before.recipes);assert.equal(up.ingredients.find(i=>i.id==='vermouth').name,'甜味美思');assert.ok(up.ingredients.find(i=>i.id==='vermouth').aliases.includes('甜红味美思'));assert.equal(up.ingredients.find(i=>i.id==='sloe-gin').matchParent,false);assert.deepEqual(C.installCatalog(up,catalog),up)});
test('目录升级不覆盖自行修改的材料归类、名称或匹配规则',()=>{const old=data();old.catalogVersion='older';const i=old.ingredients.find(i=>i.id==='vermouth');Object.assign(i,{name:'我的红味美思',parentId:'aromatized-wine',matchParent:false,customized:true});assert.deepEqual(C.installCatalog(old,catalog).ingredients.find(x=>x.id===i.id),i)});
test('目录升级移除旧的 100% 龙舌兰伪分类并迁移已有引用',()=>{const old=data(),tequila=old.ingredients.find(i=>i.id==='tequila');old.catalogVersion='older';old.ingredients.push({...tequila,id:'tequila-agave',name:'100% 龙舌兰酒',parentId:'tequila'});old.recipes[0].ingredients[0].id='tequila-agave';old.pantryItems=[{id:'old-tequila',name:'旧龙舌兰',brand:'',category:'酒精成分',image:'',matches:['tequila-agave'],tags:[]}];const upgraded=C.installCatalog(old,catalog);assert.equal(upgraded.ingredients.some(i=>i.id==='tequila-agave'),false);assert.equal(upgraded.recipes[0].ingredients[0].id,'tequila');assert.deepEqual(upgraded.pantryItems[0].matches,['tequila'])});
test('替代品引用、循环与匹配规则严格校验',()=>{let d=data();d.recipes[0].ingredients[0].alternatives=['missing'];assert.throws(()=>C.validate(d),/替代/);d=data();d.ingredients.find(i=>i.id==='gin').matchParent='false';assert.throws(()=>C.validate(d),/匹配边界/);d=data();d.ingredients.find(i=>i.id==='sloe-gin').parentId='monkey47-sloe';assert.throws(()=>C.validate(d),/循环|上级必须/)});

test('酒柜一级类目及其二级类目保持指定顺序',()=>{const d=data(),names=parent=>d.ingredients.filter(i=>i.parentId===parent).map(i=>i.name);assert.deepEqual(names('alcohol'),['威士忌','金酒','朗姆酒','龙舌兰','伏特加','白兰地','啤酒','葡萄酒','味美思','波特&雪莉','利口酒','其他酒']);assert.deepEqual(names('non-alcohol'),['气泡水','其他材料']);assert.deepEqual(names('vodka').slice(0,5),['中性伏特加','风味伏特加','中国白酒','韩国烧酒','日本烧酒']);assert.deepEqual(names('other-alcohol'),['开胃酒','阿玛罗','苦精']);assert.deepEqual(names('soda-root'),['苏打水','汤力水','其他气泡水']);assert.deepEqual(names('other-materials'),['糖浆','果汁','水果&蔬菜','调料','其他食品'])});
test('多标签配方必须由同一瓶酒同时满足',()=>{const d=data();d.ingredients.push(
 {id:'origin-cuba',name:'古巴朗姆',kind:'type',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:[]},
 {id:'style-white',name:'白朗姆标签',kind:'type',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:[]},
 {id:'cuban-white-rule',name:'古巴白朗姆',kind:'type',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:['origin-cuba','style-white']},
 {id:'bottle-both',name:'双标签酒',kind:'product',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:['origin-cuba','style-white']},
 {id:'bottle-cuba',name:'古巴酒',kind:'product',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:['origin-cuba']},
 {id:'bottle-white',name:'白朗姆',kind:'product',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:['style-white']});
 const normalized=C.validate(d),requirement=row('cuban-white-rule');own(normalized,'bottle-cuba','bottle-white');assert.equal(C.have(requirement,normalized),false);own(normalized,'bottle-both');assert.equal(C.have(requirement,normalized),true);assert.match(C.materialText(normalized.ingredients.find(i=>i.id==='bottle-both'),normalized),/古巴朗姆/)});
test('目录中的古巴白朗姆已按产地与风格拆成联合标签',()=>{const d=data(),rule=d.ingredients.find(i=>i.id==='cuban-white');assert.deepEqual(rule.tags,['cuban-rum','rum']);d.ingredients.push({id:'my-cuban-white',name:'我的古巴白朗姆',kind:'product',category:'基酒',parentId:'rum-all',brand:'',aliases:[],tags:['cuban-rum','rum']});own(d,'my-cuban-white');assert.ok(C.have(row('cuban-white'),C.validate(d)))});
test('朗姆标签将产地与风格分开，组合名称只作为配方规则',()=>{const d=data(),tags=['rum','gold-rum','dark-rum','overproof-rum','cuban-rum','jamaican-rum','puerto-rico-rum'];for(const id of tags){const i=d.ingredients.find(x=>x.id===id);assert.ok(i,id);assert.deepEqual(i.tags,[])}assert.deepEqual(d.ingredients.find(i=>i.id==='jamaican-gold').tags,['jamaican-rum','gold-rum']);assert.deepEqual(d.ingredients.find(i=>i.id==='puerto-rico-gold').tags,['puerto-rico-rum','gold-rum']);assert.deepEqual(d.ingredients.find(i=>i.id==='jamaican-dark').tags,['jamaican-rum','dark-rum'])});

test('酒柜记录的多个标签在同一瓶上按交集匹配',()=>{const d=data();d.pantryItems=[{id:'bacardi',name:'百加得白朗姆',brand:'Bacardi',category:'酒精成分',image:'',matches:['rum-all'],tags:['rum','cuban-rum']}];assert.ok(C.have(row('rum'),d));assert.ok(C.have(row('cuban-rum'),d));assert.ok(C.have(row('cuban-white'),d));d.pantryItems[0].tags=['rum'];assert.equal(C.have(row('cuban-white'),d),false)});
